In [13]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list) #np.array() is a function and used to convert a list into a numpy array
print(arr)
print(type(arr))
print(arr[0]) # indexing in numpy array is same as list

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [4]:
my_tuple = (1, 2, 3, 4, 5)
arr2 = np.array(my_tuple) # np.array() is a function and used to convert a tuple into a numpy array
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.5.1


In [5]:
arr3 = np.array(42) # np.array() is a function and used to convert a scalar into a numpy array
print(arr3)

42


In [7]:
arr4=np.array([[1,2],[3,4]])
print(arr4)

[[1 2]
 [3 4]]


In [11]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr5)
print(arr5.ndim) # ndim is a function and used to find the dimension of the array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [19]:
arr6 = np.array([1,2,3,4,5,5,6,7,8,9,10],ndmin=5) # ndim is a parameter and used to find the dimension of the array
print(arr6)
print('number of dimensions: ',arr6.ndim)
print(type(arr6))
print(arr6[0]) # its show the 5th dimension of the array 

[[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]]
number of dimensions:  5
<class 'numpy.ndarray'>
[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]
