In [13]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list) #np.array() is a function and used to convert a list into a numpy array
print(arr)
print(type(arr))
print(arr[0]) # indexing in numpy array is same as list

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [4]:
my_tuple = (1, 2, 3, 4, 5)
arr2 = np.array(my_tuple) # np.array() is a function and used to convert a tuple into a numpy array
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.5.1


In [5]:
arr3 = np.array(42) # np.array() is a function and used to convert a scalar into a numpy array
print(arr3)

42


In [7]:
arr4=np.array([[1,2],[3,4]])
print(arr4)

[[1 2]
 [3 4]]


In [11]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr5)
print(arr5.ndim) # ndim is a function and used to find the dimension of the array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [19]:
arr6 = np.array([1,2,3,4,5,5,6,7,8,9,10],ndmin=5) # ndim is a parameter and used to find the dimension of the array
print(arr6)
print('number of dimensions: ',arr6.ndim)
print(type(arr6))
print(arr6[0]) # its show the 5th dimension of the array 

[[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]]
number of dimensions:  5
<class 'numpy.ndarray'>
[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]


In [20]:
my_list2 = [[1, 2, 3], [4, 5, 6]]
arr7 = np.array(my_list2)
print(arr7)
print(arr7[0, 1]+ arr7[1, 2]) # indexing in 2D numpy array

[[1 2 3]
 [4 5 6]]
8


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2]) # indexing in 3D numpy array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [23]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element on 2nd dim: ", arr[1, -1]) # indexing in 2D numpy array with negative index 

Last element on 2nd dim:  10


In [26]:
### Slicing in Numpy Arrays in 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) # slicing in numpy array is same as list
print(arr[:5])
print(arr[1:])
print(arr[-3:-1])
print(arr[::3]) # slicing in numpy array with step

[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5 6 7]
[5 6]
[1 4 7]


In [31]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr[1, 1:4]) # slicing in 2D numpy array
print(arr[0:2, 2]) # column slicing in 2D numpy array
print(arr[0:2,0:2]) # slicing in 2D numpy array with row and column]
print(arr[0:2,4]) # slicing in 2D numpy array with row and column
print(arr[0:3,0:6])
print(arr[1:3,2:5])

[7 8 9]
[3 8]
[[1 2]
 [6 7]]
[ 5 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 8  9 10]
 [13 14 15]]


In [33]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype) # dtype is a function and used to find the data type of the array
print(type(arr))

int64
<class 'numpy.ndarray'>


In [35]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) # dtype is a function and used to find the data type of the array

<U6


In [36]:
arr = np.array([1, 2, 3, 4], dtype='S') # dtype is a parameter and used to find the data type of the array
print(arr)
print(arr.dtype) # dtype is a function and used to find the data type of the array  

[b'1' b'2' b'3' b'4']
|S1


In [37]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [38]:
arr = np.array([1, 2, 3, 4], dtype='U')

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1
