In [25]:
a = [1, 2, 3]
b = [4, 5, 6]
z = []
for i,j in zip(a,b):
    z.append(i+j)

print(z)

[5, 7, 9]


In [26]:
import numpy as np
a = [1, 2, 3]
b = [4, 5, 6]
z = np.add(a,b)
print(z)

[5 7 9]


In [27]:
import numpy as np
a = [1, 2, 3]
b = [4, 5, 6]
c = [34, 45, 56]
d = [67, 78, 89]
def my_add(x,y):
    return x+y
new_add = np.frompyfunc(my_add,2,1)
z = new_add(a,b)
print(z)
try_add1 = my_add(5,6)
print(try_add)
def my_concat(x,y):
    return str(x)+str(y)
new_concat = np.frompyfunc(my_concat,2,1)
x = new_concat(c,d)
print(x)
if type(x) == np.ufunc:
    print("x is a ufunc")
else:
    print("x is not a ufunc")
if type(z) == np.ufunc:
    print("z is a ufunc")
else:
    print("z is not a ufunc")

[5 7 9]
11
['3467' '4578' '5689']
x is not a ufunc
z is not a ufunc


In [28]:
import numpy as np
x = np.array([10,20,30,40,50,60,70,80,90,100])
y = np.array([1,2,3,4,5,6,7,8,9,10])

add1 = np.add(x,y)
subs1 = np.subtract(x,y)
mult1 = np.multiply(x,y)
div1 = np.divide(x,y)
abs1 = np.absolute(x)
divmod1 = np.divmod(x,y)

print("Addition: ",add1)
print("Subtraction: ",subs1)
print("Multiplication: ",mult1)
print("Division: ",div1)
print("Absolute: ",abs1)
print("Divmod: ",divmod1)


Addition:  [ 11  22  33  44  55  66  77  88  99 110]
Subtraction:  [ 9 18 27 36 45 54 63 72 81 90]
Multiplication:  [  10   40   90  160  250  360  490  640  810 1000]
Division:  [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
Absolute:  [ 10  20  30  40  50  60  70  80  90 100]
Divmod:  (array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [29]:
import numpy as np
arr1 = np.ceil([-3.1666,3,6667])
arr2 = np.floor([-3.1666,3.6667])
arr3 = np.trunc([-3.1666,3.6667])
#arr4 = np.fix([-3.1666,3.6667])
arr6 = np.round([-3.1666,3.6667])
arr7 = np.sign([-3.1666,3.6667])

print("Ceil: ",arr1)
print("Floor: ",arr2)
print("Trunc: ",arr3)
#print("Fix: ",arr4)
print("Round: ",arr6)
print("Sign: ",arr7)


Ceil:  [-3.000e+00  3.000e+00  6.667e+03]
Floor:  [-4.  3.]
Trunc:  [-3.  3.]
Round:  [-3.  4.]
Sign:  [-1.  1.]


In [30]:
import numpy as np

arr = np.arange(1,10)

print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))

my_log = np.frompyfunc(log,2,1)

print(my_log(100,15))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [31]:
from math import log
import numpy as np

# ২ টি ইনপুট (number, base) এবং ১ টি আউটপুটের ufunc তৈরি
nplog = np.frompyfunc(log, 2, 1)

# nplog(মান, বেস)
print(nplog(100, 15))

1.7005483074552052


In [41]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.maximum(arr1, arr2))
new_arr = np.add(arr1, arr2)
print(new_arr)
new_arr2 = np.sum([arr1, arr2])
print(new_arr2)
new_arr3 = np.sum([arr1, arr2],axis=1)
print(new_arr3)
new_arr4 = np.sum([arr1, arr2],axis=0)
print(new_arr4)
new_arr5 = np.cumsum(arr1)
print(new_arr5)
new_arr6 = np.cumsum(arr2)
print(new_arr6)

[4 5 6]
[5 7 9]
21
[ 6 15]
[5 7 9]
[1 3 6]
[ 4  9 15]


In [45]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.prod(arr1)
print(new_arr)
new_arr2 = np.prod([arr1, arr2])
print(new_arr2)
new_arr3 = np.prod([arr1, arr2], axis=0)
print(new_arr3)
new_arr4 = np.prod([arr1, arr2], axis=1)
print(new_arr4)
new_arr5 = np.cumprod(arr1)
print(new_arr5)
new_arr6 = np.cumprod(arr2)
print(new_arr6)

6
720
[ 4 10 18]
[  6 120]
[1 2 6]
[  4  20 120]


In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
new_arr = np.diff(arr1)
print(new_arr)

[1 1]


In [3]:
arr1 = np.array([5, 10, 15, 25])
new_arr = np.diff(arr1, n=2)
print(new_arr)

[0 5]


In [6]:
arr1 = np.array([1, 2, 3,12,20])
new_arr = np.lcm.reduce(arr1)
print(new_arr)

60


In [7]:
num1 = 15
num2 = 20
lcm = np.lcm(num1, num2)
print("LCM of", num1, "and", num2, "is:", lcm)

LCM of 15 and 20 is: 60


In [8]:
import numpy as np

arr1 = np.arange(1,17)
new_arr = np.lcm.reduce(arr1)
print(new_arr)

720720


In [11]:
num1 = 10
num2 = 17
gcd = np.gcd(num1, num2)
print("GCD of", num1, "and", num2, "is:", gcd)

GCD of 10 and 17 is: 1


In [14]:
arr1 = np.array([20, 8, 32, 36, 16])
new_arr = np.gcd.reduce(arr1)
print(new_arr)

4


In [15]:
import numpy as np
num1 = np.sin(np.pi/2)
print(num1)
num2 = np.cos(np.pi/2)
print(num2)
num3 = np.tan(np.pi/4)
print(num3)
num4 = np.sin([np.pi/2, np.pi/3, np.pi/4])
print(num4)

1.0
6.123233995736766e-17
0.9999999999999999
[1.         0.8660254  0.70710678]


In [19]:
import numpy as np
arr1 = np.array([np.pi/2, np.pi/3, np.pi/4,np.pi,2*np.pi,3*np.pi,3/4*np.pi,1.5*np.pi])
new_arr1 = np.rad2deg(arr1)
print(new_arr1)

[ 90.  60.  45. 180. 360. 540. 135. 270.]


In [20]:
import numpy as np
arr1 = np.array([30, 45, 60, 90, 180, 270, 360])
new_arr1 = np.deg2rad(arr1)
print(new_arr1)

[0.52359878 0.78539816 1.04719755 1.57079633 3.14159265 4.71238898
 6.28318531]


In [22]:
import numpy as np

num1 = np.arcsin(1)
print(num1)
num2 = np.arccos(0)
print(num2)
num3 = np.arctan(1)
print(num3)

num4 = np.arcsin([1, 0.5, 0])
print(num4)
num5 = np.arccos([0, 0.5, 1])
print(num5)
num6 = np.arctan([1, 0.5, 0])
print(num6)

1.5707963267948966
1.5707963267948966
0.7853981633974483
[1.57079633 0.52359878 0.        ]
[1.57079633 1.04719755 0.        ]
[0.78539816 0.46364761 0.        ]


In [25]:
import numpy as np
base = 4
perp = 3
result = np.hypot(base, perp)
print("The length of the hypotenuse is:", result)

The length of the hypotenuse is: 5.0


In [26]:
import numpy as np
x = np.sinh(np.pi/2)
print(x)
x1 = np.cosh(np.pi/2)
print(x1)
x2 = np.tanh(np.pi/2)
print(x2)

y1 = np.arcsinh(1)
print(y1)
y2 = np.arccosh(1)
print(y2)
y3 = np.arctanh(0.5)
print(y3)

z1 = np.sinh([np.pi/2, np.pi, 3*np.pi/2])
print(z1)
z2 = np.cosh([np.pi/2, np.pi, 3*np.pi/2])
print(z2)
z3 = np.tanh([np.pi/2, np.pi, 3*np.pi/2])
print(z3)



2.3012989023072947
2.5091784786580567
0.9171523356672744
0.881373587019543
0.0
0.5493061443340548
[ 2.3012989  11.54873936 55.6543976 ]
[ 2.50917848 11.59195328 55.66338089]
[0.91715234 0.99627208 0.99983861]


In [27]:
import numpy as np
arr1 = np.array([1, 2, 3,5,6,7,8,9,10,4,5,6,7,8,9])
new = np.unique(arr1)
print(new)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])
new_arr1 = np.intersect1d(arr1, arr2)
print(new_arr1)
new_arr2 = np.setdiff1d(arr1, arr2)
print(new_arr2)
new_arr3 = np.setxor1d(arr1, arr2)
print(new_arr3)
new_arr4 = np.union1d(arr1, arr2)
print(new_arr4)

[4 5]
[1 2 3]
[1 2 3 6 7 8]
[1 2 3 4 5 6 7 8]


End of numpy sheet