In [71]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list) #np.array() is a function and used to convert a list into a numpy array
print(arr)
print(type(arr))
print(arr[0]) # indexing in numpy array is same as list

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [72]:
my_tuple = (1, 2, 3, 4, 5)
arr2 = np.array(my_tuple) # np.array() is a function and used to convert a tuple into a numpy array
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [73]:
print(np.__version__)

2.5.1


In [74]:
arr3 = np.array(42) # np.array() is a function and used to convert a scalar into a numpy array
print(arr3)

42


In [75]:
arr4=np.array([[1,2],[3,4]])
print(arr4)

[[1 2]
 [3 4]]


In [76]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr5)
print(arr5.ndim) # ndim is a function and used to find the dimension of the array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [77]:
arr6 = np.array([1,2,3,4,5,5,6,7,8,9,10],ndmin=5) # ndim is a parameter and used to find the dimension of the array
print(arr6)
print('number of dimensions: ',arr6.ndim)
print(type(arr6))
print(arr6[0]) # its show the 5th dimension of the array 

[[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]]
number of dimensions:  5
<class 'numpy.ndarray'>
[[[[ 1  2  3  4  5  5  6  7  8  9 10]]]]


In [78]:
my_list2 = [[1, 2, 3], [4, 5, 6]]
arr7 = np.array(my_list2)
print(arr7)
print(arr7[0, 1]+ arr7[1, 2]) # indexing in 2D numpy array

[[1 2 3]
 [4 5 6]]
8


In [79]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2]) # indexing in 3D numpy array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [80]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element on 2nd dim: ", arr[1, -1]) # indexing in 2D numpy array with negative index 

Last element on 2nd dim:  10


In [81]:
### Slicing in Numpy Arrays in 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) # slicing in numpy array is same as list
print(arr[:5])
print(arr[1:])
print(arr[-3:-1])
print(arr[::3]) # slicing in numpy array with step

[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5 6 7]
[5 6]
[1 4 7]


In [82]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr[1, 1:4]) # slicing in 2D numpy array
print(arr[0:2, 2]) # column slicing in 2D numpy array
print(arr[0:2,0:2]) # slicing in 2D numpy array with row and column]
print(arr[0:2,4]) # slicing in 2D numpy array with row and column
print(arr[0:3,0:6])
print(arr[1:3,2:5])

[7 8 9]
[3 8]
[[1 2]
 [6 7]]
[ 5 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 8  9 10]
 [13 14 15]]


In [83]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype) # dtype is a function and used to find the data type of the array
print(type(arr))

int64
<class 'numpy.ndarray'>


In [84]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) # dtype is a function and used to find the data type of the array

<U6


In [85]:
arr = np.array([1, 2, 3, 4], dtype='S') # dtype is a parameter and used to find the data type of the array
print(arr)
print(arr.dtype) # dtype is a function and used to find the data type of the array  

[b'1' b'2' b'3' b'4']
|S1


In [86]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [87]:
arr = np.array([1, 2, 3, 4], dtype='U')

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [88]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list) # dtype is a parameter and used to find the data type of the array
print(arr)
print(arr.dtype) # dtype is a function and used to find the data type of the array
print(type(arr))
new_arr = arr.astype('f')
print(new_arr)
print(new_arr.dtype) # dtype is a function and used to find the data type of the array


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
float32


In [89]:
arr = np.array([1.1, 2.1, 3.1])
print(arr)
new_arr = arr.astype('i') # dtype is a parameter and used to find the data type of the array
print(new_arr)
print(new_arr.dtype) # dtype is a function and used to find the data type of the array

[1.1 2.1 3.1]
[1 2 3]
int32


In [90]:
arr = np.array([1, 0, 3])
print(arr)
new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype) # dtype is a function and used to find the data type of the array

[1 0 3]
[ True False  True]
bool


In [91]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = arr.astype('U') # dtype is a parameter and used to find the data type of the array
print(new_arr)
print(new_arr.dtype) # dtype is a function and used to find the data type of the array

a= arr.copy() # copy() is a function and used to create a copy of the array
b = arr.view() # view() is a function and used to create a view of the array
arr[0] = 10
print(arr)
print(a)
print(b)


['1' '2' '3' '4' '5']
<U21
[10  2  3  4  5]
[1 2 3 4 5]
[10  2  3  4  5]


In [92]:
import numpy as np

# ১. অরিজিনাল অ্যারে তৈরি
arr = np.array([1, 2, 3, 4, 5])

# ২. একটি স্লাইস তৈরি করা (এটি একটি ভিউ)
view_arr = arr[1:4]

# চেক করা
print("অরিজিনাল অ্যারের বেস:", arr.base)      # আউটপুট: None
print("ভিউ অ্যারের বেস:", view_arr.base)      # আউটপুট: [1 2 3 4 5]

অরিজিনাল অ্যারের বেস: None
ভিউ অ্যারের বেস: [1 2 3 4 5]


In [93]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) #এর মানে হলো array-টি তার ডেটা নিজেই ওন করে (এটি একটি মূল বা অরিজিনাল array)।
print(y.base) #এর মানে হলো array-টি তার ডেটা অন্য কোনো array-এর সাথে যুক্ত রয়েছে (এটি একটি view)।

None
[1 2 3 4 5]


In [94]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [12, 4, 63, 64, 234]])
 # np.array() is a function and used to convert a list into a numpy array
x= arr.shape
print(x) # shape is a function and used to find the shape of the array  

(2, 5)


In [95]:
arr = np.array([1, 2, 3, 4, 5],ndmin=5) # ndim is a parameter and used to find the dimension of the array
x = arr.copy()
y = arr.view()
print(x.base) #এর মানে হলো array-টি তার ডেটা নিজেই ওন করে (এটি একটি মূল বা অরিজিনাল array)।
print(y.base) #এর মানে হলো array-টি তার ডেটা অন্য কোনো array-এর সাথে যুক্ত রয়েছে (এটি একটি view)। 
print("the shape of the array is:", arr.shape) #it shows the shape of the array as a tuple (5, 1, 1, 1, 5) which means it has 5 dimensions with sizes 1, 1, 1, and 5 respectively.


None
[1 2 3 4 5]
the shape of the array is: (1, 1, 1, 1, 5)


In [96]:
arr = np.array([1, 2, 3, 4, 5 , 6, 7, 8, 9, 10, 11,12])
x= arr.reshape(4,3) # reshape() is a function and used to change the shape of the array 
print(x)
print("the shape of the array is:", x.shape) #it shows the shape of the array as a tuple (4, 3) which means it has 2 dimensions with sizes 4 and 3 respectively.    
print("the shape of the array is:", arr.shape) #it shows the shape of the array as a tuple (12,) which means it has 1 dimension with size 12 respectively.  
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
the shape of the array is: (4, 3)
the shape of the array is: (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [97]:
print('xihad')
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

xihad
[1 2 3 4 5]


In [98]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [99]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [100]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [101]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [102]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [103]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [104]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [105]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = arr.T # T is a function and used to transpose the array
print(arr2)

[[1 4]
 [2 5]
 [3 6]]


In [106]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.concatenate((arr1, arr2)) # concatenate() is a function and used to join two or more arrays
print(new_arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [108]:
import numpy as np
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
new_arr = np.concatenate((arr1,arr2), axis=1) # concatenate() is a function and used to join two or more arrays 
print(new_arr)



[[1 2 5 6]
 [3 4 7 8]]


In [110]:
import numpy as np 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new1 = np.vstack((arr1, arr2)) # vstack() is a function and used to join two or more arrays vertically
print("new1:", new1)
new2 = np.hstack((arr1, arr2)) # hstack() is a function and used to join two or more arrays horizontally
print("new2:", new2)
new3 = np.dstack((arr1, arr2)) # dstack() is a function and used to join two or more arrays depth wise
print("new3:", new3)

new1: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
new2: [[1 2 5 6]
 [3 4 7 8]]
new3: [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [111]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [116]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.array_split(arr,3)
print("new_arr:", new_arr)
new_arr1 = np.array_split(arr,4)
print("new_arr1:", new_arr1)
new2 = np.array_split(arr, 2)
print("new2:", new2)
new3 = np.array_split(arr, 5)
print("new3:", new3)
new4 = np.array_split(arr, 6)
print("new4:", new4)

new_arr: [array([1, 2]), array([3, 4]), array([5, 6])]
new_arr1: [array([1, 2]), array([3, 4]), array([5]), array([6])]
new2: [array([1, 2, 3]), array([4, 5, 6])]
new3: [array([1, 2]), array([3]), array([4]), array([5]), array([6])]
new4: [array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [126]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new_arr = np.array_split(arr, 3)
print("new_arr:", new_arr)
print("new_arr[0]:", new_arr[0])
print("new_arr[1]:", new_arr[1])
print("new_arr[2]:", new_arr[2])
print("new_arr[0][0]:", new_arr[0][0])
print("new_arr[0:3][1:3]:", new_arr[0:3][1:4])

new_arr: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
new_arr[0]: [[1 2]
 [3 4]]
new_arr[1]: [[5 6]
 [7 8]]
new_arr[2]: [[ 9 10]
 [11 12]]
new_arr[0][0]: [1 2]
new_arr[0:3][1:3]: [array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [127]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_arr = np.array_split(arr, 3)
print("new_arr:", new_arr)

new_arr: [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [134]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
newarr1 = np.array_split(arr, 6, axis=0)
print(newarr1)
newarr2 = np.vsplit(arr, 6) # vsplit() is a function and used to split the array vertically
print(newarr2)
newarr3 = np.hsplit(arr, 3) # hsplit() is a function and used to split the array horizontally
print(newarr3)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
new_arr = np.where(arr == 4) # where() is a function and used to find the index of the array and show as a tuple
print(new_arr)#tuple output
for x in new_arr:
  print(x) # it shows the index of the array as a list

(array([3, 5, 6]),)
[3 5 6]


In [139]:
import numpy as np
arr = np.array([1, 2, 34, 5, 6,10, 14, 93, 41, 8, 7, 12, 13, 15, 16, 17, 18, 19, 20, 21,30,32,33,34,100,104])
new_arr = np.where(arr % 2 == 0) # where() is a function and used to find the index of the array and show as a tuple
print(new_arr) 
new_arr1 = np.where(arr % 2 == 1) # where() is a function and used to find the index of the array and show as a tuple
for x in new_arr:
  print(x) # it shows the index of the array as a list
for x in new_arr1:
  print(x) 

(array([ 1,  2,  4,  5,  6,  9, 11, 14, 16, 18, 20, 21, 23, 24, 25]),)
[ 1  2  4  5  6  9 11 14 16 18 20 21 23 24 25]
[ 0  3  7  8 10 12 13 15 17 19 22]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
x= np.searchsorted(arr, 7) # searchsorted() is a function and used to find the index of the array
print(x)
new_arr = np.insert(arr, x, 7) # insert() is a function and used to insert an element at a specific index
print(new_arr)
y = np.searchsorted(arr, 15, side='right') # searchsorted() is a function and used to find the index of the array
print(y)
new1 = np.insert(arr, y, 15) # insert() is a function and used to insert an element at a specific index
print(new1)


6
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
14
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
x = np.searchsorted(arr, [2, 4, 6],side='right') # searchsorted() is a function and used to find the index of the array
print(x)
new = np.insert(arr, x, [2, 4, 6]) # insert() is a function and used to insert an element at a specific index
print(new)

[1 3 5]
[ 1  2  2  3  4  4  5  6  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30]


In [153]:
import numpy as np
arr = np.array([1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
new1 = np.sort(arr)
print(new1)
new2 = np.sort(arr)[::-1] # sort() is a function and used to sort the array in descending order
print(new2)

[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  6
  5  4  3  2  1]


In [154]:
import numpy as np
matrix = np.array([[3, 2, 4], [5, 0, 1]])
new1 = np.sort(matrix, axis=0) # sort() is a function and used to sort the array in ascending order
print(new1)
new2 = np.sort(matrix, axis=1) # sort() is a function and used to sort the array in ascending order
print(new2) 

[[3 0 1]
 [5 2 4]]
[[2 3 4]
 [0 1 5]]


In [155]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
